config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tweets
  get '/search', to: 'tweets#search', as: 'search_tweet'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @tweets = Tweet.paginate(page: params[:page], per_page: 10)
  end

  # GET /tweets/1 or /tweets/1.json
  def show; end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @termino = params[:q]
    @tweets = Tweet.where('description LIKE :termino OR username LIKE :termino', termino: "%#{@termino}%")
    @tweets = Tweet.paginate(page: params[:page], per_page: 10)
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:description, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Explorar / Twitter</title>
  <%= favicon_link_tag 'twitter.png' %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<div class="">
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_field :Description %>
  </div>

  <div>
    <%= form.label :UserName, style: "display: block" %>
    <%= form.text_field :UserName %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_header.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <% image_url = Faker::LoremFlickr.image(size: "300x300", search_terms: ['nature', 'animal']) %>
  <div class="card" style="width: 100%;">
    <div class="card-body">
      <h5 class="card-title"><%= tweet.username%></h5>
      <p> <%= tweet.description %>  </p>
      <img src="<%= image_url %>" class="card-img-top" alt="...">
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-center align-items-center">
<p style="color: green"><%= notice %></p>

<h1 class=" align-items-center">Explorar</h1>


<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
<%= link_to "New tweet", new_tweet_path %>
</div>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>
<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/search.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 fixed-column">
      <div class="sidebar">
        <div class="icon-container">
          <%= link_to "tweets" do %>
          <%= image_tag("twitter.png", alt: "Twitter Icon", class: "icon") %>
          <% end %>
          <%= link_to "search" do %>
            <%= image_tag("search.png", alt: "search Icon", class: "icon") %>
          <% end %>
          <%= image_tag("setting.png", alt: "setting Icon", class: "icon") %>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="container-main">
        <div class="row">
          <div class="col">
            <h1>Explorar</h1>
          </div>
          <div class="col">
            <%= image_tag("setting.png", alt: "setting Icon", class: "icon") %>
          </div>
        </div>
        <%= form_tag search_tweet_path, method: :get, class: "search-form" do %>
          <%= text_field_tag :q, params[:q], placeholder: 'Buscar tweets', class: "search-input" %>
          <%= submit_tag 'Buscar', class: "search-button" %>
        <% end %>
      </div>
      <h1>Resultados de búsqueda</h1>
      <% if @tweets.present? %>
        <p>Se encontraron <%= @tweets.count %> resultados para "<%= @termino %>".</p>
        <div id="tweets">
          <% @tweets.each do |tweet| %>
            <%= render tweet %>
            <div class="icon-container-tweet">
              <%= image_tag("chats.png", alt: "chats Icon", class: "icon-tweet") %>
              <%= image_tag("repost.png", alt: "repost Icon", class: "icon-tweet") %>
              <%= image_tag("love.png", alt: "love Icon", class: "icon-tweet") %>
              <%= image_tag("profit.png", alt: "profit Icon", class: "icon-tweet") %>
              <%= image_tag("share.png", alt: "share Icon", class: "icon-tweet") %>
            </div>
            <p>
              <%= link_to "Show this tweet", tweet %>
            </p>
            <%= will_paginate @tweets %>
        <% end %>
        </div>
      <% else %>
        <p>No se encontraron resultados para "<%= @termino %>".</p>
      <% end %>
    </div>
    <div class="col-lg-3 fixed-column">
      <div class="sidebar">
        <h1>¿Eres nuevo en Twitter?</h1>
        <h2 class="btn">Regístrate ahora</h2>
      </div>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>